### ISSUE TITLE
What's this for? / Grasp retreats

### ISSUE THREAD

**Issue by v4hn** [ros-interactive-manipulation/manipulation_msgs#9]
What's the long-term purpose and goal of this package?
I suppose it was an attempt to specify manipulation-related messages in a MoveIt/Arm Navigation-agnostic fashion.
But at the moment, this feels like an outdated version of https://github.com/ros-planning/moveit_msgs .
Should we aim to make MoveIt use the messages from this repository or should we remove dependencies to it? Either way, the current mix is not ideal.

Most annoyingly, this package's [Grasp.msg](https://github.com/ros-interactive-manipulation/manipulation_msgs/blob/hydro-devel/msg/Grasp.msg) only contains a `retreat` field without specifying _which_ one is meant.
[`moveit_msgs/Grasp`](https://github.com/ros-planning/moveit_msgs/blob/jade-devel/msg/Grasp.msg) on the other hand separates `post_grasp_retreat` and `post_place_retreat`.
Now that wouldn't matter too much to me, but [moveit's pick_place_capability interprets it as `post_place_retreat`](https://github.com/ros-planning/moveit/blob/kinetic-devel/moveit_ros/manipulation/move_group_pick_place_capability/src/pick_place_action_capability.cpp#L498) while the other one actually is more important to me (and is currently hard-coded...).

Should we update this in kinetic and add the field?

Also I would be interested in adding a `string pose_joint` field that specifies the joint the poses in the Grasp refer to, because this is a bit fuzzy in MoveIt at the moment...

**Comment by davetcoleman** [comment]
From my limited knowledge of these msgs, we should move away from using them.

**Comment by tfoote** [comment]
This does look like a lot of duplication. They were both started within a week of each other [a](https://github.com/ros-planning/moveit_msgs/commits/jade-devel?page=3) [b](https://github.com/ros-interactive-manipulation/manipulation_msgs/commits/hydro-devel)  And they were aware of each other since there's a [commit](https://github.com/ros-planning/moveit_msgs/commit/6c39f4cb05b265a579368efae31206b9aed4ea55) in moveit_msgs to add a dependency on manipulation_msgs

But the messages were copied in [here](https://github.com/ros-planning/moveit_msgs/commit/61a456f6583b8d13ba835c8ef219440acdcaf529) and the dependency removed. 

It's probably worth officially deprecating this in favor of the other one which has had seen more development/updates.

**Comment by v4hn** [comment]
On Tue, Aug 16, 2016 at 01:39:42PM -0700, Tully Foote wrote:

> It's probably worth officially deprecating this in favor of the other one which has had seen more development/updates.

makes sense to me.

However, it's not that easy.
This module provides the `GraspPlanning` action and service definitions among other messages that cannot be found in `moveit_msgs`.
So the intention seemed to be to separate grasp-related messages from other MoveIt messages (probably connected to the GraspIt project?).

This distinction does make sense too and I would even go ahead and propose to make MoveIt use the messages in this repository again (and update them as appropriate).

@isucan copied `Grasp.msg`, `GripperTranslation.msg`, and `PlaceLocation.msg` from here to `moveit_msgs` and it looks like he changed at least the exact point I mentioned in the issue about the retreat direction in `Grasp.msg` without mentioning the changes in a commit.
Why did he do that?

Having a dependency from here to `moveit_msgs` is not desirable, so we can't remove `Grasp` from here without moving the rest to `moveit_msgs`.

**Comment by mintar** [comment]
Yes, as you've guessed, the GraspPlanning action and service definitions are from the GraspIt project that was used together with `arm_navigation`. I don't think that has ever made it to MoveIt.

I guess the intention was this: The `manipulation_msgs` package is tightly coupled with the `arm_navigation` pipeline, so the msgs in here must not be changed. I think back in 2012 it also wasn't clear how long MoveIt and `arm_navigation` would exist in parallel. So @isucan put all the new and updated messages into `moveit_msgs`, and reused some messages from `manipulation_msgs` instead of copying them verbatim. Then later he decided to remove that dependency.

So I agree with @tfoote : Let's leave this package alone and deprecate it, and move anything that's still missing to moveit_msgs. If something is broken in moveit_msgs, fix it there. If you want to split moveit_msgs, go ahead, but I wouldn't reuse manipulation_msgs.

**Comment by davetcoleman** [comment]
+1 to @mintar and @tfoote

**Comment by v4hn** [comment]
Ok, so let's move away from this module.

I opened [an issue in the moveit repo](https://github.com/ros-planning/moveit/issues/80) to replace the service client there that still uses `manipulation_msgs/GraspPlanning.srv`.

**Comment by v4hn** [comment]
Thanks for the input everyone!
